sabnzbd:
  image: timhaak/sabnzbd
  hostname: "sikozu.local"
  restart: always
  ports:
    - "8080:8080"
    - "8090:8090"
  volumes:
    - "./volumes/sabnzbd/config:/config"
    - "./volumes/sabnzbd/scratch:/scratch"
    - "./volumes/sabnzbd/data:/data"

transmission:
  image: timhaak/transmission
  restart: always
  ports:
    - "9091:9091"
    - "51413:51413"
    - "51413:51413/udp"
  volumes:
    - "./volumes/transmission/config:/config"
    - "./volumes/transmission/scratch:/scratch"
    - "./volumes/transmission/data:/data"

sickbeard:
  image: timhaak/sickbeard
  restart: always
  ports:
    - "8081:8081"
  links:
    - sabnzbd
    - transmission
    - plex
  volumes:
    - "./volumes/sickbeard/config:/config"
    - "./volumes/sickbeard/scratch:/scratch"
    - "./volumes/sickbeard/data:/data"

couchpotato:
  image: timhaak/couchpotato
  ports:
    - "5050:5050"
  volumes:
    - "./volumes/couchpotato/config:/config"
    - "./volumes/couchpotato/data:/data"
data:
  image: busybox
  volumes:
    - "/config"
    - "/data"

plex:
  image: timhaak/plexpass
  net: "host"
  ports:
    - "32400:32400"
  volumes_from:
    - data
